### ISSUE TITLE
Installation breaks with Node 10.3.0

### ISSUE THREAD

**Issue by eliseumds** [sorccu/node-jpeg-turbo#10]
It used to work with Node 10.1.0, but then I upgraded it and got this error:

MacOS 10.13.4

```
> jpeg-turbo@0.4.0 install .../node_modules/jpeg-turbo
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/Users/eliseumds/.nvm/versions/node/v10.3.0/bin/node',
node-pre-gyp verb cli   '.../node_modules/jpeg-turbo/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.19
node-pre-gyp info using node@10.3.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for ".../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64/jpegturbo.node" (not found)
node-pre-gyp http GET https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v64-darwin-x64.tar.gz
node-pre-gyp http 403 https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v64-darwin-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v64-darwin-x64.tar.gz (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp http Connection closed while downloading tarball file (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_0 Release/obj/gen/jfdctflt-sse-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_0 Release/obj/gen/jfdctflt-sse-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_1 Release/obj/gen/jccolor-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_1 Release/obj/gen/jccolor-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_2 Release/obj/gen/jcgray-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_2 Release/obj/gen/jcgray-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_3 Release/obj/gen/jcsample-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_3 Release/obj/gen/jcsample-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_4 Release/obj/gen/jdcolor-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_4 Release/obj/gen/jdcolor-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_5 Release/obj/gen/jdmerge-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_5 Release/obj/gen/jdmerge-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_6 Release/obj/gen/jdsample-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_6 Release/obj/gen/jdsample-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_7 Release/obj/gen/jfdctfst-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_7 Release/obj/gen/jfdctfst-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_8 Release/obj/gen/jfdctint-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_8 Release/obj/gen/jfdctint-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_9 Release/obj/gen/jidctflt-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_9 Release/obj/gen/jidctflt-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_10 Release/obj/gen/jidctfst-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_10 Release/obj/gen/jidctfst-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_11 Release/obj/gen/jidctint-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_11 Release/obj/gen/jidctint-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_12 Release/obj/gen/jidctred-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_12 Release/obj/gen/jidctred-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_13 Release/obj/gen/jquantf-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_13 Release/obj/gen/jquantf-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_14 Release/obj/gen/jquanti-sse2-64.o
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_14 Release/obj/gen/jquanti-sse2-64.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcapimin.o
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcapimin.o
rm: ./Release/.deps/Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcapimin.o.d.raw: No such file or directory
make: *** [Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcapimin.o] Error 1
gyp   CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jcapistd.o
ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/eliseumds/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/eliseumds/.nvm/versions/node/v10.3.0/bin/node" "/Users/eliseumds/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=.../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64/jpegturbo.node" "--module_name=jpegturbo" "--module_path=.../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd .../node_modules/jpeg-turbo
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/eliseumds/.nvm/versions/node/v10.3.0/bin/node /Users/eliseumds/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=.../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64/jpegturbo.node --module_name=jpegturbo --module_path=.../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (.../node_modules/jpeg-turbo/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/Users/eliseumds/.nvm/versions/node/v10.3.0/bin/node" ".../node_modules/jpeg-turbo/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd .../node_modules/jpeg-turbo
node-pre-gyp ERR! node -v v10.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.19
node-pre-gyp ERR! not ok
Failed to execute '/Users/eliseumds/.nvm/versions/node/v10.3.0/bin/node /Users/eliseumds/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=.../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64/jpegturbo.node --module_name=jpegturbo --module_path=.../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64' (1)
  CC(target) Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jccoefct.o Failed to exec install script
make: *** No rule to make target `../deps/libjpeg-turbo/jccolor.c', needed by `Release/obj.target/jpeg-turbo/deps/libjpeg-turbo/jccolor.o'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/eliseumds/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/eliseumds/.nvm/versions/node/v10.3.0/bin/node" "/Users/eliseumds/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=.../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64/jpegturbo.node" "--module_name=jpegturbo" "--module_path=.../node_modules/jpeg-turbo/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd .../node_modules/jpeg-turbo
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN html-webpack-plugin@3.2.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mocha-prepare@0.1.0 requires a peer of mocha@>=1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-lazyload@2.3.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-lazyload@2.3.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN productreview-e2e@0.0.0 No description
npm WARN productreview-e2e@0.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jpeg-turbo@0.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jpeg-turbo@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eliseumds/.npm/_logs/2018-06-06T02_38_24_259Z-debug.log
```

**Comment by sagimann** [comment]
Also with node 10.16. Any updates?

**Comment by zoolyka** [comment]
I doubt that it will be ever fixed for node 10.3.+ :(
Currently the fastest implementation is: https://github.com/LinusU/cwasm-jpeg-turbo
