### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by zhfnjust** [sorccu/node-jpeg-turbo#11]
$ yarn add jpeg-turbo > 1.log
warning jpeg-turbo > node-pre-gyp > hawk > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning jpeg-turbo > node-pre-gyp > hawk > sntp > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning jpeg-turbo > node-pre-gyp > hawk > boom > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
error F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.9.4 | win32 | x64
node-pre-gyp info check checked for "F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64\jpegturbo.node" (not found)
node-pre-gyp http GET https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v57-win32-x64.tar.gz
node-pre-gyp http 403 https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for jpeg-turbo@0.4.0 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://pre-gyp.s3.amazonaws.com/jpegturbo/v0.4.0/jpegturbo-v0.4.0-node-v57-win32-x64.tar.gz

F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp info ok

F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64\jpegturbo.node --module_name=jpegturbo --module_path=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64\jpegturbo.node --module_name=jpegturbo --module_path=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64 )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\code\\vnc\\electron-webpack-quick-start\\node_modules\\jpeg-turbo\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.node-gyp\\8.9.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.node-gyp\\8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.node-gyp\\8.9.4\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\code\\vnc\\electron-webpack-quick-start\\node_modules\\jpeg-turbo',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\code\\vnc\\electron-webpack-quick-start\\node_modules\\jpeg-turbo\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64\jpegturbo.node --module_name=jpegturbo --module_path=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64 )  else (node "" build --fallback-to-build --module=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64\jpegturbo.node --module_name=jpegturbo --module_path=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64 )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�
  Building "F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\build\Release\obj/global_intermediate/jfdctflt-sse-64.obj"
  yasm: FATAL: unable to open include file `jsimdcfg.inc'
F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\build\deps\jpeg-turbo.targets(28,5): error MSB3721: ���call yasm "-felf" "-o" "F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\build\Release\obj\global_intermediate\jfdctflt-sse-64.obj" "..\..\deps\libjpeg-turbo\simd\jfdctflt-sse-64.asm"�����˳������ش���Ϊ 1�� [F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\build\deps\jpeg-turbo.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=F:\\code\\vnc\\electron-webpack-quick-start\\node_modules\\jpeg-turbo\\lib\\binding\\node-v57-win32-x64\\jpegturbo.node" "--module_name=jpegturbo" "--module_path=F:\\code\\vnc\\electron-webpack-quick-start\\node_modules\\jpeg-turbo\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64\jpegturbo.node --module_name=jpegturbo --module_path=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\code\vnc\electron-webpack-quick-start\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\code\\vnc\\electron-webpack-quick-start\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64\jpegturbo.node --module_name=jpegturbo --module_path=F:\code\vnc\electron-webpack-quick-start\node_modules\jpeg-turbo\lib\binding\node-v57-win32-x64' (1)

**Comment by eard7** [comment]
I'm getting the same error, does anybody have a solution?
